; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes
; RUN: opt -passes='gemm-replacer-pass,loop-deletion,dce,simplifycfg,loop-deletion,dce,simplifycfg' --gemmfarer-replacement-mode=matrix-intrinsics -S < %s | FileCheck %s

define void @_Z14staticSizeGEMMPKdiS0_iPdidd(double* %A, i32 %lda, double* %B, i32 %ldb, double* %C, i32 %ldc, double %alpha, double %beta) {
; CHECK-LABEL: @_Z14staticSizeGEMMPKdiS0_iPdidd(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = sext i32 [[LDA:%.*]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = sext i32 [[LDB:%.*]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = sext i32 [[LDC:%.*]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = call <1024 x double> @llvm.matrix.column.major.load.v1024f64.i64(double* align 8 [[A:%.*]], i64 [[TMP0]], i1 false, i32 16, i32 64)
; CHECK-NEXT:    [[TMP4:%.*]] = call <512 x double> @llvm.matrix.column.major.load.v512f64.i64(double* align 8 [[B:%.*]], i64 [[TMP1]], i1 false, i32 8, i32 64)
; CHECK-NEXT:    [[TMP5:%.*]] = call <512 x double> @llvm.matrix.transpose.v512f64(<512 x double> [[TMP4]], i32 8, i32 64)
; CHECK-NEXT:    [[TMP6:%.*]] = call <128 x double> @llvm.matrix.multiply.v128f64.v1024f64.v512f64(<1024 x double> [[TMP3]], <512 x double> [[TMP5]], i32 16, i32 64, i32 8)
; CHECK-NEXT:    [[SCALAR_SPLAT_SPLATINSERT:%.*]] = insertelement <128 x double> poison, double [[ALPHA:%.*]], i32 0
; CHECK-NEXT:    [[SCALAR_SPLAT_SPLAT:%.*]] = shufflevector <128 x double> [[SCALAR_SPLAT_SPLATINSERT]], <128 x double> poison, <128 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = fmul <128 x double> [[SCALAR_SPLAT_SPLAT]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = call <128 x double> @llvm.matrix.column.major.load.v128f64.i64(double* align 8 [[C:%.*]], i64 [[TMP2]], i1 false, i32 8, i32 16)
; CHECK-NEXT:    [[TMP9:%.*]] = call <128 x double> @llvm.matrix.transpose.v128f64(<128 x double> [[TMP8]], i32 8, i32 16)
; CHECK-NEXT:    [[SCALAR_SPLAT_SPLATINSERT1:%.*]] = insertelement <128 x double> poison, double [[BETA:%.*]], i32 0
; CHECK-NEXT:    [[SCALAR_SPLAT_SPLAT2:%.*]] = shufflevector <128 x double> [[SCALAR_SPLAT_SPLATINSERT1]], <128 x double> poison, <128 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP10:%.*]] = fmul <128 x double> [[SCALAR_SPLAT_SPLAT2]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = fadd <128 x double> [[TMP7]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = call <128 x double> @llvm.matrix.transpose.v128f64(<128 x double> [[TMP11]], i32 16, i32 8)
; CHECK-NEXT:    call void @llvm.matrix.column.major.store.v128f64.i64(<128 x double> [[TMP12]], double* align 8 [[C]], i64 [[TMP2]], i1 false, i32 8, i32 16)
; CHECK-NEXT:    ret void
;
entry:
  %0 = sext i32 %lda to i64
  %1 = sext i32 %ldb to i64
  %2 = sext i32 %ldc to i64
  br label %for.cond1.preheader

for.cond1.preheader:                              ; preds = %entry, %for.cond.cleanup3
  %indvars.iv67 = phi i64 [ 0, %entry ], [ %indvars.iv.next68, %for.cond.cleanup3 ]
  %3 = mul nsw i64 %indvars.iv67, %2
  br label %for.cond5.preheader

for.cond.cleanup:                                 ; preds = %for.cond.cleanup3
  ret void

for.cond5.preheader:                              ; preds = %for.cond1.preheader, %for.cond.cleanup7
  %indvars.iv63 = phi i64 [ 0, %for.cond1.preheader ], [ %indvars.iv.next64, %for.cond.cleanup7 ]
  br label %for.body8

for.cond.cleanup3:                                ; preds = %for.cond.cleanup7
  %indvars.iv.next68 = add nuw nsw i64 %indvars.iv67, 1
  %exitcond70.not = icmp eq i64 %indvars.iv.next68, 16
  br i1 %exitcond70.not, label %for.cond.cleanup, label %for.cond1.preheader

for.cond.cleanup7:                                ; preds = %for.body8
  %mul15 = fmul double %add14, %alpha
  %4 = add nsw i64 %indvars.iv63, %3
  %arrayidx19 = getelementptr inbounds double, double* %C, i64 %4
  %5 = load double, double* %arrayidx19, align 8
  %mul20 = fmul double %5, %beta
  %add21 = fadd double %mul15, %mul20
  store double %add21, double* %arrayidx19, align 8
  %indvars.iv.next64 = add nuw nsw i64 %indvars.iv63, 1
  %exitcond66.not = icmp eq i64 %indvars.iv.next64, 8
  br i1 %exitcond66.not, label %for.cond.cleanup3, label %for.cond5.preheader

for.body8:                                        ; preds = %for.cond5.preheader, %for.body8
  %indvars.iv = phi i64 [ 0, %for.cond5.preheader ], [ %indvars.iv.next, %for.body8 ]
  %c.055 = phi double [ 0.000000e+00, %for.cond5.preheader ], [ %add14, %for.body8 ]
  %6 = mul nsw i64 %indvars.iv, %0
  %7 = add nsw i64 %6, %indvars.iv67
  %arrayidx = getelementptr inbounds double, double* %A, i64 %7
  %8 = load double, double* %arrayidx, align 8
  %9 = mul nsw i64 %indvars.iv, %1
  %10 = add nsw i64 %9, %indvars.iv63
  %arrayidx12 = getelementptr inbounds double, double* %B, i64 %10
  %11 = load double, double* %arrayidx12, align 8
  %mul13 = fmul double %8, %11
  %add14 = fadd double %c.055, %mul13
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 64
  br i1 %exitcond.not, label %for.cond.cleanup7, label %for.body8
}
